/* automatically generated by rust-bindgen 0.60.1 */

pub const IBLLib_Result_Success: IBLLib_Result = 0;
pub const IBLLib_Result_VulkanInitializationFailed: IBLLib_Result = 1;
pub const IBLLib_Result_VulkanError: IBLLib_Result = 2;
pub const IBLLib_Result_InputPanoramaFileNotFound: IBLLib_Result = 3;
pub const IBLLib_Result_ShaderFileNotFound: IBLLib_Result = 4;
pub const IBLLib_Result_ShaderCompilationFailed: IBLLib_Result = 5;
pub const IBLLib_Result_FileNotFound: IBLLib_Result = 6;
pub const IBLLib_Result_InvalidArgument: IBLLib_Result = 7;
pub const IBLLib_Result_KtxError: IBLLib_Result = 8;
pub const IBLLib_Result_StbError: IBLLib_Result = 9;
pub type IBLLib_Result = ::std::os::raw::c_uint;
pub const IBLLib_OutputFormat_R8G8B8A8_UNORM: IBLLib_OutputFormat = 37;
pub const IBLLib_OutputFormat_R16G16B16A16_SFLOAT: IBLLib_OutputFormat = 97;
pub const IBLLib_OutputFormat_R32G32B32A32_SFLOAT: IBLLib_OutputFormat = 109;
pub type IBLLib_OutputFormat = ::std::os::raw::c_int;
pub const IBLLib_Distribution_None: IBLLib_Distribution = 0;
pub const IBLLib_Distribution_Lambertian: IBLLib_Distribution = 1;
pub const IBLLib_Distribution_GGX: IBLLib_Distribution = 2;
pub const IBLLib_Distribution_Charlie: IBLLib_Distribution = 3;
pub type IBLLib_Distribution = ::std::os::raw::c_uint;
extern "C" {
    pub fn IBLSample(
        _inputPath: *const ::std::os::raw::c_char,
        _outputPathCubeMap: *const ::std::os::raw::c_char,
        _outputPathLUT: *const ::std::os::raw::c_char,
        _distribution: IBLLib_Distribution,
        _cubemapResolution: ::std::os::raw::c_uint,
        _mipmapCount: ::std::os::raw::c_uint,
        _sampleCount: ::std::os::raw::c_uint,
        _targetFormat: IBLLib_OutputFormat,
        _lodBias: f32,
        _debugOutput: bool,
    ) -> IBLLib_Result;
}
